development:
  STRIPE_PUBLISHABLE_KEY: pk_test_HOTzzL5ascAk71ggsLDyaXgW
  STRIPE_SECRET_KEY: sk_test_9SZCzWtrn9rSdujINLt8Urum
  MW_LEARNERS_KEY: 296ba566-058e-45a6-9a58-e62253ff0238

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_HOTzzL5ascAk71ggsLDyaXgW
  STRIPE_SECRET_KEY: sk_test_9SZCzWtrn9rSdujINLt8Urum
  MW_LEARNERS_KEY: 296ba566-058e-45a6-9a58-e62253ff0238

production:
  STRIPE_PUBLISHABLE_KEY: pk_live_PtMVo1eS1MNNZYRebk7hYCwE
  STRIPE_SECRET_KEY: sk_live_4SzzwbeveL6iouqEgufxFMVi
  MW_LEARNERS_KEY: 296ba566-058e-45a6-9a58-e62253ff0238